name: "Build Mac application"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP: PrivateDropMac
defaults:
  run:
    working-directory: ./

jobs:
  format-swift:
    runs-on: macos-11.0
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2 # checkout root
        with: 
          submodules: true 
      - name: "Install swift-format"
        run: brew install swift-format
      - name: "Run swift-format"
        run: swift-format --recursive --mode lint .

  build-app:
    runs-on: macos-11.0
    needs:
      - format-swift
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Checkout submodules"
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: "Select Xcode 12"
        uses: devbotsxyz/xcode-select@v1
        with:
          version: "12"
      - name: "Archive project"
        run: xcodebuild archive -scheme PrivateDrop\ Mac -workspace PrivateDrop.xcworkspace  -configuration release -archivePath ${APP}.xcarchive
